# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20160530_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
