# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 02:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('todo', '0007_auto_20160530_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC')),
            ],
        ),
    ]
