# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('deadline',)},
        ),
    ]
